apiVersion: v1                
kind: Service                 
metadata:                     
  name: petclinic    
  labels:                     
    app: petclinic
spec:                         
  type: NodePort              
  selector:
    app: petclinic   
  ports:                      
  - name: http
    port: 8080
    targetPort: 8080