apiVersion: apps/v1
kind: Deployment                    
metadata:
  name: petclinic-mysql           
  labels:                           
    app: petclinic
spec:
  selector:
    matchLabels:                    
      app: petclinic
      tier: mysql
  strategy:
    type: Recreate
  template:                         
    metadata:
      labels:                       
        app: petclinic
        tier: mysql
    spec:                          
      containers:
      - image: mysql:5.6
        name: mysql
        env:                        
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:                
            secretKeyRef:
              name: mysql-root
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-datasource-url
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-app
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-app
              key: password
        ports:
        - containerPort: 3306        
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage  
          mountPath: /var/lib/mysql
      volumes:                       
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim