apiVersion: v1                    
kind: Service                     
metadata:
  name: petclinic-mysql         
  labels:                         
    app: petclinic
spec:
  ports:
    - port: 3306
  selector:                         
    app: petclinic
    tier: mysql
  clusterIP: None