apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1024Mi
  accessModes:
    - ReadWriteOnce
  hostPath:                       
    path: "/User/petclinic"
  persistentVolumeReclaimPolicy: Retain