apiVersion: apps/v1
kind: Deployment              
metadata:
  name: petclinic    
  labels:                     
    app: petclinic
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:              
      app: petclinic
  template:                   
    metadata:
      labels:                 
        app: petclinic
    spec:                     
      containers:
      {{- range $containerIndex, $container := .Values.containers }}
      - name: {{ $container.name | default "container" | quote }}
        image: {{ $container.image | quote }}
        imagePullPolicy: {{ $container.imagePullPolicy | quote }}
        ports:
          - name: http
            containerPort: 8080 
      {{- if $container.resources }}
        resources:
          {{- with $container.resources.limits }}
          limits:
            cpu: {{ .cpu }}
            memory: {{ .memory | quote }}
          {{- end }}
      {{- end }}
      {{- end }}
        env:                  
        - name: SPRING_DATASOURCE_USERNAME  
          value: "root"
          # valueFrom:     
          #   secretKeyRef:
          #     name: mysql-app
          #     key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root
              key: password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: mysql-datasource-url
              key: url